config/routes.rb
PleaseWork::Application.routes.draw do
  resources :travelers
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'travelers#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :date_trip, :feelings, :people, :place, :transport
  belongs_to :traveler, :foreign_key => "user_id"
  
  validates :user_id, presence: true
  validates :date_trip, presence: true
  validates :place, presence: true
  validates :people, presence: true
  validates :transport, presence: true
  validates :feelings, presence: true, length: { maximum: 200 }
  
  default_scope order: 'comments.created_at DESC'
end

app/models/traveler.rb
class Traveler < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
  has_secure_password
  has_many :comments, dependent: :destroy, :foreign_key => "user_id"
  
  before_save { |traveler| traveler.email = email.downcase }
  before_save :create_remember_token
  
  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :signed_in_traveler, only: [:create, :destroy]
  before_filtre :correct_traveler,   only: :destroy

  def create
    @comment = current_traveler.comments.build(params[:comment])
    if @comment.save
      flash[:success] = "Comment was successfully created!"
      redirect_to root_url
    else
	  @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_url
  end

  private

    def correct_traveler
      @comment = current_traveler.comments.find_by_id(params[:id])
      redirect_to root_url if @comment.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    traveler = Traveler.find_by_email(params[:session][:email].downcase)
    if traveler && traveler.authenticate(params[:session][:password])
      sign_in traveler
	  redirect_back_or traveler
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
	sign_out
	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @comment  = current_traveler.comments.build
      @feed_items = current_traveler.comments.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/travelers_controller.rb
class TravelersController < ApplicationController
  before_filter :signed_in_traveler, only: [:index, :edit, :update, :destroy]
  before_filter :correct_traveler,   only: [:edit, :update]
  before_filter :admin_user,         only: :destroy

  def show
    @traveler = Traveler.find(params[:id])
	@comments = @traveler.comments.paginate(page: params[:page])
  end
  
  def destroy
    Traveler.find(params[:id]).destroy
    flash[:success] = "Traveler destroyed."
    redirect_to travelers_url
  end
  
  def new
    @traveler = Traveler.new
  end
  
  def index
    @travelers = Traveler.paginate(page: params[:page])
  end
  
  def create
    @traveler = Traveler.new(params[:traveler])
	if @traveler.save
	  sign_in @traveler
	  flash[:success] = "Welcome to the Traveler's family!"
	  redirect_to @traveler
	else
	  render 'new'
	end
  end
  
  def edit
  end
  
  def update
	if @traveler.update_attributes(params[:traveler])
	  flash[:success] = "Profile was successfully updated"
	  sign_in @traveler
	  redirect_to @traveler
	else
		render 'edit'
	end
  end
  
  private
	
	def signed_in_traveler
	  unless signed_in?
	    store_location
	    redirect_to signin_url, notice: "Please sign in."
	  end
	end
	
	def correct_traveler
	  @traveler = Traveler.find(params[:id])
	  redirect_to(root_path) unless current_traveler?(@traveler)
	end
	
	def admin_user
      redirect_to(root_path) unless current_traveler.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Welcome to the Travelers Application"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(traveler)
    cookies.permanent[:remember_token] = traveler.remember_token
    self.current_traveler = traveler
  end
  
  def signed_in?
	!current_traveler.nil?
  end
  
  def current_traveler=(traveler)
    @current_traveler = traveler
  end
  
  def current_traveler
    @current_traveler ||= Traveler.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_traveler?(traveler)
    traveler == current_traveler
  end
  
  def signed_in_traveler
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
  
  def sign_out
	self.current_traveler = nil
	cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/travelers_helper.rb
module TravelersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(traveler, options = { size: 52 })
    gravatar_id = Digest::MD5::hexdigest(traveler.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: traveler.last_name, class: "gravatar")
  end
end

app/views/comments/_comment.html.erb
<li>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
  <% if current_traveler?(comment.traveler) %>
    <%= link_to "delete", comment, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: comment.feelings %>
  <% end %>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "traveler page", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Travelers", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_traveler %></li>
                <li><%= link_to "Settings", edit_traveler_path(current_traveler) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	   <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    Date of your trip<br />
    <%= f.date_select :date_trip %>
  </div>
  
  <div class="field">
    What place did you visit?<br />
    <%= f.text_field :place %>
  </div>
  
  <div class="field">
    How many people were traveling with you?<br />
    <%= f.number_field :people %>
  </div>
  
  <div class="field">
    What transport did you use?<br />
    <%= f.text_field :transport %>
  </div>
  
  <div class="field">
    Tell us your feeling about the trip:<br />
    <%= f.text_area :feelings %>
  </div>
  
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="comments">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.traveler), feed_item.traveler %>
  <span class="traveler">
    <%= link_to feed_item.traveler.last_name, feed_item.traveler %>
  </span>
  <span class="feelings"><%= feed_item.feelings %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_traveler?(feed_item.traveler) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.feelings %>
  <% end %>
</li>

app/views/shared/_traveler_info.html.erb
<a href="<%= traveler_path(current_traveler) %>">
  <%= gravatar_for current_traveler, size: 52 %>
</a>
<h1>
  <%= current_traveler.last_name %>
</h1>
<span>
  <%= link_to "view my profile", current_traveler %>
</span>
<span>
  <%= pluralize(current_traveler.comments.count, "comment") %>
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/traveler_info' %>
      </section>
      <section>
        <%= render 'shared/comment_form' %>
      </section>
    </aside>
	
	<div class="span8">
      <h3>Feelings Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>  
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Traveler page</h1>

    <%= link_to "Sign up now!", signup_path, 
                                class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 

app/views/travelers/_traveler.html.erb
<li>
  <%= gravatar_for traveler, size: 52 %>
  <%= link_to traveler.last_name, traveler %>
  <% if !current_traveler.admin? && !current_traveler?(traveler) %>
    | <%= link_to "delete", traveler, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/travelers/edit.html.erb
<% provide(:title, "Edit traveler") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@traveler) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
	  
	  <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @traveler %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/travelers/index.html.erb
<% provide(:title, 'All travelers') %>
<h1>All travelers</h1>

<%= will_paginate %>

<ul class="travelers">
  <%= render @travelers %>
</ul>

<%= will_paginate %>

app/views/travelers/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@traveler) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
	  
	  <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/travelers/show.html.erb
<% provide(:title, @traveler.first_name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @traveler %>
        <%= @traveler.last_name %>
      </h1>
    </section>
  </aside>
 <div class="span8">
    <% if @traveler.comments.any? %>
      <h3>Comments (<%= @traveler.comments.count %>)</h3>
      <ol class="comments">
        <%= render @comments %>
      </ol>
      <%= will_paginate @comments %>
    <% end %>
  </div>
</div>